apiVersion: apps/v1
kind: Deployment
metadata:
  name: cybersyn-app
spec:
  selector:
    matchLabels:
      app: cybersyn-app
  replicas: 10
  template:
    metadata:
      labels:
        app: cybersyn-app
    spec:
      containers:
      - name: cybersyn-app
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
